### ISSUE TITLE
`--set-output` deprecated

### ISSUE THREAD

**Issue by aswen** [howijd/actions-set-markdown-output#5]
I've read a warning that the `--set-output` command is [on the way out](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

Your example solution is nice. may do with an update.

**Comment by mkungla** [comment]
Fixed in PR #4

**Comment by dja** [comment]
@mkungla it looks like a new release needs to be published for this to go out.

**Comment by mkungla** [comment]
released, should be ok now
